language: cpp
compiler:
  - gcc
before_script:
 - mkdir build
 - cd build
 - cmake .. -DMYGUI_STATIC=1
before_install:
 - git submodule update --init --recursive
 - echo "yes" | sudo apt-add-repository ppa:openmw/deps
 - sudo apt-get update -qq
 - sudo apt-get remove -qq libogre-static-dev
 - sudo apt-get install -qq libois-dev libopenal-dev libpng-dev libogre-dev libmpg123-dev libsndfile1-dev libblkid-dev libfreeimage-dev libboost-filesystem-dev libboost-thread-dev libboost-chrono-dev libboost-program-options-dev libboost-system-dev libboost-wave-dev uuid-dev libqt4-opengl libqt4-dev libavcodec-dev libavformat-dev libavdevice-dev libavutil-dev libswscale-dev libpostproc-dev ffmpeg libbullet-dev libmygui-dev libqt4-dev libgtest-dev google-mock zziplib-bin libcg libav-tools libois-dev libopenal-dev libxaw7-dev 
script: make
branches:
  only:
    - master
    - travis_ci_test
notifications:
  recipients:
    - lgromanowski+travis.ci@gmail.com
  email:
    on_success: change
    on_failure: always
