os:
 - linux
language: cpp
sudo: required
dist: trusty
branches:
  only:
    - master
    - coverity_scan
    - /openmw-.*$/
    - doxygen
addons:
  apt:
    sources:
      - sourceline: 'ppa:openmw/openmw'
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages: [
      # Dev
      clang-3.6, libunshield-dev, libtinyxml-dev,
      # Tests
      libgtest-dev, google-mock,
      # Boost
      libboost-filesystem-dev, libboost-program-options-dev, libboost-system-dev, libboost-thread-dev,
      # FFmpeg
      libavcodec-dev, libavformat-dev, libavutil-dev, libswscale-dev,
      # Audio & Video
      libsdl2-dev, libqt4-dev, libopenal-dev,
      # The other ones from OpenMW ppa
      libbullet-dev, libswresample-dev, libopenscenegraph-3.4-dev, libmygui-dev,

      doxygen, doxygen-doc, doxygen-latex, doxygen-gui, graphviz
    ]

before_install: ./CI/before_install.${TRAVIS_OS_NAME}.sh
before_script: ./CI/before_script.${TRAVIS_OS_NAME}.sh
script: ./CI/generateDocumentationAndDeploy.sh
