language: cpp
compiler:
  - clang
  - gcc
before_script:
 - mkdir build
 - cd build
 - cmake ..
before_install:
 - git submodule update --init --recursive
 - sudo apt-add-repository ppa:openmw/deps
 - sudo apt-get update -qq
 - sudo apt-get install -qq ffmpeg-dev boost-dev libbullet libogre-static mygui-static
script: make
branches:
  only:
    - master
    - travis_ci_test
notifications:
  recipients:
    - lgromanowski+travis.ci@gmail.com
  email:
    on_success: change
    on_failure: always
