os:
 - linux
 - osx
language: cpp
branches:
  only:
    - master
    - coverity_scan
    - /openmw-.*$/
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "CcQGmzgaBRTPWqPZLoLX4Zkt5pOQb5c6Pr5OFt15C8xQRhWOLrWcdsQEO1UuEJ70/YJgbvN+wQk8B5COBDLxM1roBNBu7zMpK//393Qx3rL2f9PdaZGLaCEtS5DyuXimyUXWzjMt8gsnsBxtomTgHBY4E7F5ag0Ub2z6ZsIQE1A="

addons:
  coverity_scan:
    project:
      name: "scrawl/openmw"
      description: "<Your project description here>"
    notification_email: scrawl@baseoftrash.de
    build_command_prepend: "cmake ."
    build_command:   "make -j4"
    branch_pattern: coverity_scan

before_install:
 - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then ./CI/before_install.linux.sh; fi
 - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then ./CI/before_install.osx.sh; fi
before_script:
 - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then ./CI/before_script.linux.sh; fi
 - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then ./CI/before_script.osx.sh; fi
script:
 - cd ./build
 - if [ "$COVERITY_SCAN_BRANCH" != 1 ]; then make -j4; fi
after_script:
 - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then ./openmw_test_suite; fi
notifications:
  recipients:
    - corrmage+travis-ci@gmail.com
  email:
    on_success: change
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#openmw"
    on_success: change
    on_failure: always
    use_notice: true
