language: cpp
compiler:
  - clang
  - gcc
before_script:
 - mkdir build
 - cd build
 - cmake .. -DMYGUI_STATIC=1
before_install:
 - git submodule update --init --recursive
 - echo "yes" | sudo apt-add-repository ppa:openmw/deps
 - sudo apt-get update -qq
 - sudo apt-get remove -qq libogre-static-dev
 - sudo apt-get install -qq ffmpeg libboost-all-dev libbullet-dev libogre-dev libmygui-static-dev libqt4-dev libgtest-dev google-mock zziplib-bin libmpg123-dev libcg libav-tools libois-dev libopenal-dev libxaw7-dev 
script: make
branches:
  only:
    - master
    - travis_ci_test
notifications:
  recipients:
    - lgromanowski+travis.ci@gmail.com
  email:
    on_success: change
    on_failure: always
