version: "{build}"

platform:
    - Win32
    - x64

configuration:
    - Debug

environment:
    matrix:
    - STEP: openmw
    - STEP: opencs
    - STEP: misc

matrix:
    fast_finish: true

os: unstable

clone_depth: 1

cache:
    - C:\projects\openmw\deps\ffmpeg32-2.5.2.7z
    - C:\projects\openmw\deps\ffmpeg32-2.5.2-dev.7z
    - C:\projects\openmw\deps\ffmpeg64-2.5.2.7z
    - C:\projects\openmw\deps\ffmpeg64-2.5.2-dev.7z

init:
    - cmd: bash --version
    - cmd: cmake --version
    - cmd: msbuild /version
    - cmd: echo.

clone_folder: C:\projects\openmw

build_script:
    - cmd: bash --login C:\projects\openmw\CI\build.msvc.sh

before_build:
    - cmd: bash --login C:\projects\openmw\CI\before_script.msvc.sh

test: off
