version: "{build}"

platform:
    - Win32
    - x64

configuration:
    - Debug
    - Release

matrix:
    fast_finish: true

init:
    - cmd: cmake --version
    - cmd: msbuild /version

clone_folder: C:\projects\openmw

build_script:
    - cmd: sh C:\projects\openmw\CI\build.msvc.sh %platform% %configuration%

before_build:
    - cmd: sh C:\projects\openmw\CI\before_script.msvc.sh %platform%
