version: "{build}"

branches:
    only:
        - appveyor

platform:
    - Win32
    - x64

configuration: Debug

environment:
    matrix:
        - STEP: misc
#        - STEP: components # misc builds this too
# Build takes too long for these, ignore for now
#        - STEP: openmw
#        - STEP: opencs

matrix:
    fast_finish: true

os: unstable

clone_depth: 1

cache:
    - C:\projects\openmw\deps\Bullet-2.83.5-win32.7z
    - C:\projects\openmw\deps\Bullet-2.83.5-win64.7z
    - C:\projects\openmw\deps\MyGUI-3.2.2-win32.7z
    - C:\projects\openmw\deps\MyGUI-3.2.2-win64.7z
    - C:\projects\openmw\deps\OSG-3.3.8-win32.7z
    - C:\projects\openmw\deps\OSG-3.3.8-win64.7z
    - C:\projects\openmw\deps\ffmpeg32-2.5.2.7z
    - C:\projects\openmw\deps\ffmpeg32-2.5.2-dev.7z
    - C:\projects\openmw\deps\ffmpeg64-2.5.2.7z
    - C:\projects\openmw\deps\ffmpeg64-2.5.2-dev.7z

clone_folder: C:\projects\openmw

before_build:
    - cmd: sh %APPVEYOR_BUILD_FOLDER%\CI\before_script.msvc.sh

build_script:
    - cmd: if %PLATFORM%==Win32 set build=Build_32
    - cmd: if %PLATFORM%==x64 set build=Build_64
    - cmd: msbuild %build%\OpenMW.sln /t:Build /p:Configuration=%configuration% /m:2 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

test: off
